"""Frozen Phase 1 schema. Do not import application ORM models."""

import sqlalchemy as sa
from alembic import op

PHASE1_TABLES = [
    "users",
    "roles",
    "user_roles",
    "role_permissions",
    "user_permissions",
    "org_units",
    "user_geography_scopes",
    "programmes",
    "user_programme_scopes",
    "org_unit_mappings",
    "org_unit_groups",
    "org_unit_group_members",
    "geometries",
    "indicators",
    "indicator_versions",
    "indicator_source_mappings",
    "period_population_rules",
    "population_versions",
    "population_values",
    "facility_population_entries",
    "raw_aggregate_values",
    "raw_event_snapshots",
    "calculation_runs",
    "calculated_values",
    "data_quality_flags",
    "saved_views",
    "export_jobs",
    "ai_requests",
    "audit_log",
]


def _now_col(name: str) -> sa.Column:
    return sa.Column(
        name,
        sa.DateTime(timezone=True),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        nullable=False,
    )


def _ts() -> list:
    return [_now_col("created_at"), _now_col("updated_at")]


def upgrade_phase1() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("username", sa.String(80), nullable=False),
        sa.Column("display_name", sa.String(200), nullable=False),
        sa.Column("email", sa.String(255)),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("is_system_admin", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("identity_provider", sa.String(50), nullable=False, server_default="local_dev"),
        sa.Column("external_subject", sa.String(255)),
        *_ts(),
        sa.UniqueConstraint("username"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("code", sa.String(80), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("description", sa.Text()),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        *_ts(),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Uuid(), sa.ForeignKey("users.id"), primary_key=True),
        sa.Column("role_id", sa.Uuid(), sa.ForeignKey("roles.id"), primary_key=True),
        sa.UniqueConstraint("user_id", "role_id"),
    )
    op.create_table(
        "role_permissions",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("role_id", sa.Uuid(), sa.ForeignKey("roles.id"), nullable=False),
        sa.Column("action", sa.String(80), nullable=False),
        sa.UniqueConstraint("role_id", "action"),
    )
    op.create_table(
        "user_permissions",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("user_id", sa.Uuid(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("action", sa.String(80), nullable=False),
        sa.UniqueConstraint("user_id", "action"),
    )
    op.create_table(
        "org_units",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("code", sa.String(80), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("level_type", sa.String(40), nullable=False),
        sa.Column("parent_id", sa.Uuid(), sa.ForeignKey("org_units.id")),
        sa.Column("path", sa.String(1000), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("valid_from", sa.Date()),
        sa.Column("valid_to", sa.Date()),
        sa.Column("ownership", sa.String(80)),
        sa.Column("facility_level", sa.String(40)),
        *_ts(),
        sa.UniqueConstraint("code"),
    )
    op.create_index("ix_org_units_parent_id", "org_units", ["parent_id"])
    op.create_index("ix_org_units_path", "org_units", ["path"])
    op.create_table(
        "user_geography_scopes",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("user_id", sa.Uuid(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("org_unit_id", sa.Uuid(), sa.ForeignKey("org_units.id"), nullable=False),
        *_ts(),
        sa.UniqueConstraint("user_id", "org_unit_id"),
    )
    op.create_table(
        "programmes",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("code", sa.String(40), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("description", sa.Text()),
        sa.Column("first_release", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("sensitive", sa.Boolean(), nullable=False, server_default=sa.false()),
        *_ts(),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "user_programme_scopes",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("user_id", sa.Uuid(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("programme_id", sa.Uuid(), sa.ForeignKey("programmes.id"), nullable=False),
        *_ts(),
        sa.UniqueConstraint("user_id", "programme_id"),
    )
    op.create_table(
        "org_unit_mappings",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("org_unit_id", sa.Uuid(), sa.ForeignKey("org_units.id"), nullable=False),
        sa.Column("source_system", sa.String(40), server_default="dhis2"),
        sa.Column("external_uid", sa.String(80), nullable=False),
        sa.Column("valid_from", sa.Date()),
        sa.Column("valid_to", sa.Date()),
        *_ts(),
        sa.UniqueConstraint("source_system", "external_uid", "valid_from"),
    )
    op.create_table(
        "org_unit_groups",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("code", sa.String(80), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("group_type", sa.String(80), nullable=False),
        sa.Column("valid_from", sa.Date()),
        sa.Column("valid_to", sa.Date()),
        sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true()),
        *_ts(),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "org_unit_group_members",
        sa.Column("group_id", sa.Uuid(), sa.ForeignKey("org_unit_groups.id"), primary_key=True),
        sa.Column("org_unit_id", sa.Uuid(), sa.ForeignKey("org_units.id"), primary_key=True),
        sa.UniqueConstraint("group_id", "org_unit_id"),
    )
    op.create_table(
        "geometries",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("org_unit_id", sa.Uuid(), sa.ForeignKey("org_units.id"), nullable=False),
        sa.Column("geojson", sa.JSON()),
        sa.Column("geometry_kind", sa.String(20), nullable=False, server_default="polygon"),
        sa.Column("source", sa.String(200)),
        sa.Column("valid_from", sa.Date()),
        sa.Column("valid_to", sa.Date()),
        *_ts(),
    )
    op.create_table(
        "indicators",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("code", sa.String(80), nullable=False),
        sa.Column("programme_id", sa.Uuid(), sa.ForeignKey("programmes.id"), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("description", sa.Text()),
        sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true()),
        *_ts(),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "indicator_versions",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("indicator_id", sa.Uuid(), sa.ForeignKey("indicators.id"), nullable=False),
        sa.Column("formula_version", sa.String(40), nullable=False),
        sa.Column("numerator_definition", sa.Text(), nullable=False),
        sa.Column("denominator_type", sa.String(40), nullable=False),
        sa.Column("denominator_coefficient", sa.Float()),
        sa.Column("denominator_reference_indicator_id", sa.Uuid(), sa.ForeignKey("indicators.id")),
        sa.Column("multiplier", sa.Float(), nullable=False, server_default="100"),
        sa.Column("unit", sa.String(80), nullable=False),
        sa.Column("display_precision", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("direction", sa.String(40), nullable=False),
        sa.Column("target", sa.String(80)),
        sa.Column("green_band", sa.String(120)),
        sa.Column("yellow_band", sa.String(120)),
        sa.Column("red_band", sa.String(120)),
        sa.Column("blue_rule", sa.Text()),
        sa.Column("aggregation_method", sa.String(40), nullable=False, server_default="sum_then_calculate"),
        sa.Column("period_adjustment", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("methodology_text", sa.Text()),
        sa.Column("quality_rules", sa.JSON()),
        sa.Column("formula_spec", sa.JSON()),
        sa.Column("classification_spec", sa.JSON()),
        sa.Column("valid_from", sa.Date()),
        sa.Column("valid_to", sa.Date()),
        sa.Column("is_current", sa.Boolean(), nullable=False, server_default=sa.true()),
        *_ts(),
        sa.UniqueConstraint("indicator_id", "formula_version"),
    )
    op.create_table(
        "indicator_source_mappings",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("indicator_version_id", sa.Uuid(), sa.ForeignKey("indicator_versions.id"), nullable=False),
        sa.Column("source_system", sa.String(40), server_default="dhis2"),
        sa.Column("semantic_field", sa.String(120), nullable=False),
        sa.Column("data_element_uid", sa.String(80)),
        sa.Column("category_option_combo_uid", sa.String(80)),
        sa.Column("program_uid", sa.String(80)),
        sa.Column("program_stage_uid", sa.String(80)),
        sa.Column("aggregation_behaviour", sa.String(80)),
        sa.Column("mapping_version", sa.String(40), nullable=False, server_default="v1"),
        sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("notes", sa.Text()),
        sa.Column("item_kind", sa.String(40)),
        sa.Column("valid_from", sa.Date()),
        sa.Column("valid_to", sa.Date()),
        *_ts(),
    )
    op.create_table(
        "period_population_rules",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("financial_year_key", sa.String(20), nullable=False),
        sa.Column("population_year", sa.Integer(), nullable=False),
        sa.Column("programme_id", sa.Uuid(), sa.ForeignKey("programmes.id")),
        sa.Column("notes", sa.Text()),
        *_ts(),
        sa.UniqueConstraint("financial_year_key", "programme_id"),
    )
    op.create_table(
        "population_versions",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("code", sa.String(80), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("source_name", sa.String(255), nullable=False),
        sa.Column("source_document", sa.String(500)),
        sa.Column("population_type", sa.String(80), nullable=False),
        sa.Column("approval_status", sa.String(40), nullable=False, server_default="draft"),
        sa.Column("valid_from", sa.Date()),
        sa.Column("valid_to", sa.Date()),
        sa.Column("notes", sa.Text()),
        sa.Column("imported_by_user_id", sa.Uuid(), sa.ForeignKey("users.id")),
        *_ts(),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "population_values",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("version_id", sa.Uuid(), sa.ForeignKey("population_versions.id"), nullable=False),
        sa.Column("org_unit_id", sa.Uuid(), sa.ForeignKey("org_units.id"), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("population", sa.Numeric(18, 2), nullable=False),
        *_ts(),
        sa.UniqueConstraint("version_id", "org_unit_id", "year"),
    )
    op.create_table(
        "facility_population_entries",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("org_unit_id", sa.Uuid(), sa.ForeignKey("org_units.id"), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("population", sa.Numeric(18, 2), nullable=False),
        sa.Column("source_name", sa.String(255), nullable=False),
        sa.Column("population_type", sa.String(80), nullable=False),
        sa.Column("approval_status", sa.String(40), nullable=False, server_default="draft"),
        sa.Column("notes", sa.Text()),
        sa.Column("reason", sa.Text()),
        sa.Column("entered_by_user_id", sa.Uuid(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("approved_by_user_id", sa.Uuid(), sa.ForeignKey("users.id")),
        sa.Column("superseded_by_id", sa.Uuid(), sa.ForeignKey("facility_population_entries.id")),
        *_ts(),
    )
    op.create_table(
        "raw_aggregate_values",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("source_system", sa.String(40), nullable=False),
        sa.Column("org_unit_id", sa.Uuid(), sa.ForeignKey("org_units.id"), nullable=False),
        sa.Column("period", sa.String(40), nullable=False),
        sa.Column("source_metric_id", sa.String(120), nullable=False),
        sa.Column("internal_source_key", sa.String(120)),
        sa.Column("dhis2_org_unit_uid", sa.String(80)),
        sa.Column("dhis2_item_uid", sa.String(80)),
        sa.Column("category_option_combo_uid", sa.String(80)),
        sa.Column("value", sa.Numeric(20, 6)),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_freshness_at", sa.DateTime(timezone=True)),
        sa.Column("source_version", sa.String(80)),
        sa.Column("mapping_version", sa.String(40)),
        sa.Column("absence_reason", sa.String(40)),
        sa.Column("checksum", sa.String(128)),
        sa.Column("is_current", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("superseded_by_id", sa.Uuid(), sa.ForeignKey("raw_aggregate_values.id")),
        sa.Column("provenance", sa.JSON()),
        *_ts(),
    )
    op.create_index("ix_raw_aggregate_values_period", "raw_aggregate_values", ["period"])
    op.create_index("ix_raw_aggregate_values_internal_source_key", "raw_aggregate_values", ["internal_source_key"])
    op.create_index(
        "uq_raw_aggregate_current",
        "raw_aggregate_values",
        ["org_unit_id", "period", "internal_source_key"],
        unique=True,
        sqlite_where=sa.text("is_current = 1"),
        postgresql_where=sa.text("is_current"),
    )
    op.create_table(
        "raw_event_snapshots",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("event_uid", sa.String(80), nullable=False),
        sa.Column("source_connector", sa.String(40), nullable=False, server_default="tracker"),
        sa.Column("program_uid", sa.String(80)),
        sa.Column("program_stage_uid", sa.String(80)),
        sa.Column("org_unit_id", sa.Uuid(), sa.ForeignKey("org_units.id"), nullable=False),
        sa.Column("status", sa.String(20), nullable=False, server_default="ACTIVE"),
        sa.Column("occurred_at", sa.DateTime(timezone=True)),
        sa.Column("completed_at", sa.DateTime(timezone=True)),
        sa.Column("source_created_at", sa.DateTime(timezone=True)),
        sa.Column("source_updated_at", sa.DateTime(timezone=True)),
        sa.Column("death_date", sa.Date()),
        sa.Column("notification_date", sa.Date()),
        sa.Column("review_date", sa.Date()),
        sa.Column("data_values", sa.JSON()),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("mapping_version", sa.String(40)),
        sa.Column("snapshot_hash", sa.String(128)),
        sa.Column("is_current", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("superseded_by_id", sa.Uuid(), sa.ForeignKey("raw_event_snapshots.id")),
        sa.Column("privacy_class", sa.String(40), nullable=False, server_default="restricted_event"),
        *_ts(),
    )
    op.create_index(
        "uq_raw_event_current",
        "raw_event_snapshots",
        ["event_uid", "source_connector"],
        unique=True,
        sqlite_where=sa.text("is_current = 1"),
        postgresql_where=sa.text("is_current"),
    )
    op.create_table(
        "calculation_runs",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("geography_org_unit_id", sa.Uuid(), sa.ForeignKey("org_units.id")),
        sa.Column("period", sa.String(40), nullable=False),
        sa.Column("programme_id", sa.Uuid(), sa.ForeignKey("programmes.id")),
        sa.Column("population_version_id", sa.Uuid(), sa.ForeignKey("population_versions.id")),
        sa.Column("indicator_set_version", sa.String(80)),
        sa.Column("source_extracted_at", sa.DateTime(timezone=True)),
        sa.Column("mapping_version", sa.String(80)),
        sa.Column("initiated_by_user_id", sa.Uuid(), sa.ForeignKey("users.id")),
        sa.Column("notes", sa.Text()),
        sa.Column("status", sa.String(40), nullable=False, server_default="queued"),
        sa.Column("duration_ms", sa.Integer()),
        sa.Column("quality_flag_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("config_snapshot", sa.JSON()),
        sa.Column("started_at", sa.DateTime(timezone=True)),
        sa.Column("finished_at", sa.DateTime(timezone=True)),
        sa.Column("error_code", sa.String(80)),
        *_ts(),
    )
    op.create_table(
        "calculated_values",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("calculation_run_id", sa.Uuid(), sa.ForeignKey("calculation_runs.id"), nullable=False),
        sa.Column("indicator_version_id", sa.Uuid(), sa.ForeignKey("indicator_versions.id"), nullable=False),
        sa.Column("org_unit_id", sa.Uuid(), sa.ForeignKey("org_units.id"), nullable=False),
        sa.Column("period", sa.String(40), nullable=False),
        sa.Column("numerator", sa.Numeric(20, 6)),
        sa.Column("denominator", sa.Numeric(20, 6)),
        sa.Column("raw_value", sa.Numeric(20, 8)),
        sa.Column("display_value", sa.String(40)),
        sa.Column("status", sa.String(20)),
        sa.Column("performance_status", sa.String(20)),
        sa.Column("quality_status", sa.String(20)),
        sa.Column("unit", sa.String(80)),
        sa.Column("direction", sa.String(40)),
        sa.Column("target", sa.String(80)),
        sa.Column("display_precision", sa.Integer()),
        sa.Column("population_year", sa.Integer()),
        sa.Column("mapping_version", sa.String(40)),
        sa.Column("source_freshness_at", sa.DateTime(timezone=True)),
        sa.Column("methodology_ref", sa.String(120)),
        sa.Column("blue_reason", sa.Text()),
        sa.Column("quality_flag_ids", sa.JSON()),
        sa.Column("population_version_id", sa.Uuid(), sa.ForeignKey("population_versions.id")),
        *_ts(),
        sa.UniqueConstraint("calculation_run_id", "indicator_version_id", "org_unit_id", "period"),
    )
    op.create_table(
        "data_quality_flags",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("rule_id", sa.String(80), nullable=False),
        sa.Column("rule_version", sa.String(40)),
        sa.Column("category", sa.String(40)),
        sa.Column("severity", sa.String(20), server_default="WARNING"),
        sa.Column("status", sa.String(20), server_default="open"),
        sa.Column("org_unit_id", sa.Uuid(), sa.ForeignKey("org_units.id")),
        sa.Column("programme_id", sa.Uuid(), sa.ForeignKey("programmes.id")),
        sa.Column("indicator_id", sa.Uuid(), sa.ForeignKey("indicators.id")),
        sa.Column("period", sa.String(40)),
        sa.Column("source_key", sa.String(120)),
        sa.Column("event_uid", sa.String(80)),
        sa.Column("evidence", sa.JSON()),
        sa.Column("explanation", sa.Text()),
        sa.Column("calculation_run_id", sa.Uuid(), sa.ForeignKey("calculation_runs.id")),
        sa.Column("resolution_note", sa.Text()),
        sa.Column("resolved_by_user_id", sa.Uuid(), sa.ForeignKey("users.id")),
        sa.Column("resolved_at", sa.DateTime(timezone=True)),
        sa.Column("acknowledged_by_user_id", sa.Uuid(), sa.ForeignKey("users.id")),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True)),
        _now_col("first_detected_at"),
        _now_col("last_detected_at"),
        *_ts(),
    )
    op.create_table(
        "saved_views",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("user_id", sa.Uuid(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("geography_org_unit_id", sa.Uuid(), sa.ForeignKey("org_units.id")),
        sa.Column("programme_id", sa.Uuid(), sa.ForeignKey("programmes.id")),
        sa.Column("period_rule", sa.String(80)),
        sa.Column("comparison_period", sa.String(80)),
        sa.Column("configuration", sa.JSON()),
        *_ts(),
    )
    op.create_table(
        "export_jobs",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("user_id", sa.Uuid(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("export_type", sa.String(40), nullable=False),
        sa.Column("status", sa.String(20), nullable=False, server_default="queued"),
        sa.Column("org_unit_id", sa.Uuid(), sa.ForeignKey("org_units.id")),
        sa.Column("programme_id", sa.Uuid(), sa.ForeignKey("programmes.id")),
        sa.Column("period", sa.String(40)),
        sa.Column("calculation_run_id", sa.Uuid(), sa.ForeignKey("calculation_runs.id")),
        sa.Column("template_version", sa.String(80)),
        sa.Column("error_code", sa.String(80)),
        *_ts(),
    )
    op.create_table(
        "ai_requests",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("user_id", sa.Uuid(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("task", sa.String(80), nullable=False),
        sa.Column("provider", sa.String(80)),
        sa.Column("model", sa.String(120)),
        sa.Column("evidence_hash", sa.String(128)),
        sa.Column("calculation_run_id", sa.Uuid(), sa.ForeignKey("calculation_runs.id")),
        sa.Column("sensitivity_class", sa.String(40), nullable=False, server_default="public_aggregate"),
        sa.Column("token_usage", sa.JSON()),
        sa.Column("status", sa.String(20), nullable=False, server_default="queued"),
        *_ts(),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("actor_user_id", sa.Uuid(), sa.ForeignKey("users.id")),
        sa.Column("action", sa.String(80), nullable=False),
        sa.Column("resource_type", sa.String(80), nullable=False),
        sa.Column("resource_id", sa.String(80)),
        sa.Column("before_json", sa.JSON()),
        sa.Column("after_json", sa.JSON()),
        sa.Column("reason", sa.Text()),
        sa.Column("ip_address", sa.String(80)),
        _now_col("created_at"),
    )
    op.create_index("ix_audit_log_action", "audit_log", ["action"])


def downgrade_phase1() -> None:
    for name in reversed(PHASE1_TABLES):
        op.drop_table(name)
