"""Canonical MNCH/EPI/MPDSR formula configuration. No DHIS2 UIDs live here."""

from __future__ import annotations

from app.domain.enums import (
    AggregationMethod,
    DenominatorType,
    FormulaKind,
    IndicatorDirection,
    Over100Behaviour,
    ProgrammeCode,
)

# Semantic source keys. Mappings bind these to DHIS2 UIDs in configuration, never in formulas.
ANC1 = "ANC1"
ANC1_FT = "ANC1_FT"
ANC4 = "ANC4"
ANC8 = "ANC8"
IPT3 = "IPT3"
HB_TESTED = "HB_TESTED"
IFA_30 = "IFA_30"
ULTRASOUND = "ULTRASOUND"
ANC1_AGE_LT15 = "ANC1_AGE_LT15"
ANC1_AGE_15_19 = "ANC1_AGE_15_19"
DELIVERIES = "DELIVERIES"
CS = "CS"
KMC_PERCENT = "KMC_PERCENT"
RESUSCITATED = "RESUSCITATED"
BIRTH_ASPHYXIA = "BIRTH_ASPHYXIA"
FRESH_SB = "FRESH_SB"
MACERATED_SB = "MACERATED_SB"
NEWBORN_DEATHS = "NEWBORN_DEATHS"
MATERNAL_DEATHS = "MATERNAL_DEATHS"
LIVE_BIRTHS = "LIVE_BIRTHS"

PERINATAL_DEATH_KEYS = (FRESH_SB, MACERATED_SB, NEWBORN_DEATHS)


def _higher(green_min: float, yellow_min: float) -> dict:
    return {"mode": "higher_is_better", "green_min": green_min, "yellow_min": yellow_min}


def _lower_max(green_max: float, yellow_max: float) -> dict:
    return {"mode": "lower_is_better", "green_max": green_max, "yellow_max": yellow_max}


def _pop(coefficient: float) -> dict:
    return {"mode": "population", "coefficient": coefficient, "period_adjust": True}


def _src(*keys: str) -> dict:
    return {"mode": "source_keys", "source_keys": list(keys), "period_adjust": False}


def _ratio(num: list[str], den: dict, **extra) -> dict:
    spec = {"kind": FormulaKind.RATIO.value, "numerator_keys": num, "denominator": den}
    spec.update(extra)
    return spec


def _indicator(
    *,
    code: str,
    name: str,
    programme: str,
    numerator: str,
    denom_type: DenominatorType,
    coefficient: float | None,
    multiplier: float,
    unit: str,
    direction: IndicatorDirection,
    target: str | None,
    green: str | None,
    yellow: str | None,
    red: str | None,
    blue: str | None,
    period_adjust: bool,
    formula_spec: dict,
    classification_spec: dict,
    aggregation: str = AggregationMethod.SUM_THEN_CALCULATE.value,
    precision: int = 1,
) -> dict:
    return {
        "code": code,
        "name": name,
        "programme": programme,
        "numerator_definition": numerator,
        "denominator_type": denom_type.value,
        "denominator_coefficient": coefficient,
        "multiplier": multiplier,
        "unit": unit,
        "direction": direction.value,
        "target": target,
        "green_band": green,
        "yellow_band": yellow,
        "red_band": red,
        "blue_rule": blue,
        "period_adjustment": period_adjust,
        "aggregation_method": aggregation,
        "display_precision": precision,
        "formula_spec": formula_spec,
        "classification_spec": classification_spec,
        "methodology_text": "Canonical MNCH/EPI/MPDSR rule. Engine reads this versioned specification.",
    }


INDICATOR_CATALOG: list[dict] = [
    _indicator(
        code="ANC1_COVERAGE",
        name="ANC1 Coverage",
        programme=ProgrammeCode.MNCH.value,
        numerator="ANC1",
        denom_type=DenominatorType.POPULATION_DERIVED,
        coefficient=0.05,
        multiplier=100,
        unit="%",
        direction=IndicatorDirection.HIGHER_IS_BETTER,
        target="95%",
        green=">=95%",
        yellow="75.0-94.9%",
        red="<75%",
        blue="Values >100% remain visible; not automatically BLUE.",
        period_adjust=True,
        formula_spec=_ratio(
            [ANC1],
            _pop(0.05),
            over_100=Over100Behaviour.RETAIN_PERFORMANCE.value,
            bounded_proportion=False,
        ),
        classification_spec=_higher(95, 75),
    ),
    _indicator(
        code="ANC1_FIRST_TRIMESTER",
        name="First-trimester ANC",
        programme=ProgrammeCode.MNCH.value,
        numerator="ANC1 first trimester",
        denom_type=DenominatorType.SERVICE_DERIVED,
        coefficient=None,
        multiplier=100,
        unit="%",
        direction=IndicatorDirection.HIGHER_IS_BETTER,
        target="45%",
        green=">=45%",
        yellow="30.0-44.9%",
        red="<30%",
        blue=None,
        period_adjust=False,
        formula_spec=_ratio([ANC1_FT], _src(ANC1), over_100=Over100Behaviour.FLAG_ONLY.value),
        classification_spec=_higher(45, 30),
    ),
    _indicator(
        code="ANC4_COVERAGE",
        name="ANC4 Coverage",
        programme=ProgrammeCode.MNCH.value,
        numerator="ANC4",
        denom_type=DenominatorType.POPULATION_DERIVED,
        coefficient=0.05,
        multiplier=100,
        unit="%",
        direction=IndicatorDirection.HIGHER_IS_BETTER,
        target="75%",
        green=">=75%",
        yellow="50.0-74.9%",
        red="<50%",
        blue=None,
        period_adjust=True,
        formula_spec=_ratio([ANC4], _pop(0.05), over_100=Over100Behaviour.RETAIN_PERFORMANCE.value),
        classification_spec=_higher(75, 50),
    ),
    _indicator(
        code="ANC8_COVERAGE",
        name="ANC8 Coverage",
        programme=ProgrammeCode.MNCH.value,
        numerator="ANC8",
        denom_type=DenominatorType.POPULATION_DERIVED,
        coefficient=0.05,
        multiplier=100,
        unit="%",
        direction=IndicatorDirection.HIGHER_IS_BETTER,
        target="15%",
        green=">=15%",
        yellow="7.0-14.9%",
        red="<7%",
        blue=None,
        period_adjust=True,
        formula_spec=_ratio([ANC8], _pop(0.05), over_100=Over100Behaviour.RETAIN_PERFORMANCE.value),
        classification_spec=_higher(15, 7),
    ),
    _indicator(
        code="IPT3_COVERAGE",
        name="IPT3 Coverage",
        programme=ProgrammeCode.MNCH.value,
        numerator="IPT3",
        denom_type=DenominatorType.POPULATION_DERIVED,
        coefficient=0.05,
        multiplier=100,
        unit="%",
        direction=IndicatorDirection.HIGHER_IS_BETTER,
        target="75%",
        green=">=75%",
        yellow="50.0-74.9%",
        red="<50%",
        blue=None,
        period_adjust=True,
        formula_spec=_ratio([IPT3], _pop(0.05), over_100=Over100Behaviour.RETAIN_PERFORMANCE.value),
        classification_spec=_higher(75, 50),
    ),
    _indicator(
        code="HB_TESTING",
        name="Hb testing",
        programme=ProgrammeCode.MNCH.value,
        numerator="Hb tested",
        denom_type=DenominatorType.SERVICE_DERIVED,
        coefficient=None,
        multiplier=100,
        unit="%",
        direction=IndicatorDirection.HIGHER_IS_BETTER,
        target="75%",
        green=">=75%",
        yellow="50.0-74.9%",
        red="<50%",
        blue=None,
        period_adjust=False,
        formula_spec=_ratio([HB_TESTED], _src(ANC1), over_100=Over100Behaviour.FLAG_ONLY.value),
        classification_spec=_higher(75, 50),
    ),
    _indicator(
        code="IFA_COVERAGE",
        name="Iron/Folic Acid",
        programme=ProgrammeCode.MNCH.value,
        numerator="women receiving ≥30 IFA tablets",
        denom_type=DenominatorType.SERVICE_DERIVED,
        coefficient=None,
        multiplier=100,
        unit="%",
        direction=IndicatorDirection.HIGHER_IS_BETTER,
        target="95%",
        green=">=95%",
        yellow="75.0-94.9%",
        red="<75%",
        blue="Preserve >100% and raise a definition/reporting quality flag.",
        period_adjust=False,
        formula_spec=_ratio([IFA_30], _src(ANC1), over_100=Over100Behaviour.FLAG_ONLY.value),
        classification_spec=_higher(95, 75),
    ),
    _indicator(
        code="OBSTETRIC_ULTRASOUND",
        name="Obstetric ultrasound",
        programme=ProgrammeCode.MNCH.value,
        numerator="women receiving ultrasound",
        denom_type=DenominatorType.SERVICE_DERIVED,
        coefficient=None,
        multiplier=100,
        unit="%",
        direction=IndicatorDirection.HIGHER_IS_BETTER,
        target="75%",
        green=">=75%",
        yellow="50.0-74.9%",
        red="<50%",
        blue=None,
        period_adjust=False,
        formula_spec=_ratio([ULTRASOUND], _src(ANC1), over_100=Over100Behaviour.FLAG_ONLY.value),
        classification_spec=_higher(75, 50),
    ),
    _indicator(
        code="TEENAGE_PREGNANCY",
        name="Teenage pregnancy among ANC1 attendees",
        programme=ProgrammeCode.MNCH.value,
        numerator="ANC1 age <15 + ANC1 age 15–19",
        denom_type=DenominatorType.SERVICE_DERIVED,
        coefficient=None,
        multiplier=100,
        unit="%",
        direction=IndicatorDirection.LOWER_IS_BETTER,
        target="<5%",
        green="<5%",
        yellow="5.0-12.9%",
        red=">=13%",
        blue=None,
        period_adjust=False,
        formula_spec=_ratio(
            [ANC1_AGE_LT15, ANC1_AGE_15_19],
            _src(ANC1),
            over_100=Over100Behaviour.FLAG_ONLY.value,
            require_all_components=True,
        ),
        classification_spec={"mode": "teenage_pregnancy", "precision": 1},
    ),
    _indicator(
        code="INSTITUTIONAL_DELIVERY",
        name="Institutional Delivery Coverage",
        programme=ProgrammeCode.MNCH.value,
        numerator="Total deliveries",
        denom_type=DenominatorType.POPULATION_DERIVED,
        coefficient=0.0485,
        multiplier=100,
        unit="%",
        direction=IndicatorDirection.HIGHER_IS_BETTER,
        target="65%",
        green=">=65%",
        yellow="50.0-64.9%",
        red="<50%",
        blue="May exceed 100%; do not automatically mark BLUE.",
        period_adjust=True,
        formula_spec=_ratio(
            [DELIVERIES],
            _pop(0.0485),
            over_100=Over100Behaviour.RETAIN_PERFORMANCE.value,
            bounded_proportion=False,
        ),
        classification_spec=_higher(65, 50),
    ),
    _indicator(
        code="CAESAREAN_SECTION",
        name="Caesarean section rate",
        programme=ProgrammeCode.MNCH.value,
        numerator="caesarean sections",
        denom_type=DenominatorType.SERVICE_DERIVED,
        coefficient=None,
        multiplier=100,
        unit="%",
        direction=IndicatorDirection.DESIRED_RANGE,
        target="5.0-15.0%",
        green="5.0-15.0%",
        yellow="3.0-4.9% or 15.1-20.0%",
        red="<3.0% or >20.0%",
        blue=None,
        period_adjust=False,
        formula_spec=_ratio([CS], _src(DELIVERIES), over_100=Over100Behaviour.FLAG_ONLY.value),
        classification_spec={
            "mode": "desired_range",
            "green": [5.0, 15.0],
            "yellow": [[3.0, 4.9], [15.1, 20.0]],
            "precision": 1,
        },
    ),
    _indicator(
        code="KMC",
        name="LBW babies initiated on KMC",
        programme=ProgrammeCode.MNCH.value,
        numerator="KMC percentage supplied by source",
        denom_type=DenominatorType.DIRECT_PERCENTAGE,
        coefficient=None,
        multiplier=1,
        unit="%",
        direction=IndicatorDirection.HIGHER_IS_BETTER,
        target="95%",
        green="95.0-100.0%",
        yellow="75.0-94.9%",
        red="<75%",
        blue=">100% is BLUE.",
        period_adjust=False,
        aggregation=AggregationMethod.DIRECT_ONLY.value,
        formula_spec={
            "kind": FormulaKind.DIRECT_PERCENTAGE.value,
            "source_key": KMC_PERCENT,
            "over_100": Over100Behaviour.NON_ASSESSABLE.value,
            "bounded_proportion": True,
        },
        classification_spec={"mode": "bounded_higher", "green_min": 95, "yellow_min": 75, "cap": 100},
    ),
    _indicator(
        code="SUCCESSFUL_RESUSCITATION",
        name="Successful resuscitation",
        programme=ProgrammeCode.MNCH.value,
        numerator="successfully resuscitated",
        denom_type=DenominatorType.SERVICE_DERIVED,
        coefficient=None,
        multiplier=100,
        unit="%",
        direction=IndicatorDirection.HIGHER_IS_BETTER,
        target="90%",
        green="90.0-100.0%",
        yellow="70.0-89.9%",
        red="<70%",
        blue=">100% is BLUE; denominator zero is N/A.",
        period_adjust=False,
        formula_spec=_ratio(
            [RESUSCITATED],
            _src(BIRTH_ASPHYXIA),
            over_100=Over100Behaviour.NON_ASSESSABLE.value,
            bounded_proportion=True,
        ),
        classification_spec={"mode": "bounded_higher", "green_min": 90, "yellow_min": 70, "cap": 100},
    ),
    _indicator(
        code="PMR",
        name="Perinatal Mortality Rate",
        programme=ProgrammeCode.MNCH.value,
        numerator="Fresh SB + Macerated SB + Newborn deaths",
        denom_type=DenominatorType.SERVICE_DERIVED,
        coefficient=None,
        multiplier=1000,
        unit="per 1,000 deliveries",
        direction=IndicatorDirection.LOWER_IS_BETTER,
        target="<=12",
        green="<=12",
        yellow=">12-20",
        red=">20",
        blue="Never display as a percentage.",
        period_adjust=False,
        formula_spec=_ratio(list(PERINATAL_DEATH_KEYS), _src(DELIVERIES), require_all_components=True),
        classification_spec=_lower_max(12, 20),
    ),
    _indicator(
        code="FRESH_STILLBIRTH_RATE",
        name="Fresh stillbirth rate",
        programme=ProgrammeCode.MNCH.value,
        numerator="fresh stillbirths",
        denom_type=DenominatorType.SERVICE_DERIVED,
        coefficient=None,
        multiplier=1000,
        unit="per 1,000 deliveries",
        direction=IndicatorDirection.LOWER_IS_BETTER,
        target="<=5",
        green="<=5",
        yellow=">5-10",
        red=">10",
        blue="Never display as a percentage.",
        period_adjust=False,
        formula_spec=_ratio([FRESH_SB], _src(DELIVERIES)),
        classification_spec=_lower_max(5, 10),
    ),
    _indicator(
        code="MMR",
        name="Maternal Mortality Ratio",
        programme=ProgrammeCode.MNCH.value,
        numerator="Maternal deaths",
        denom_type=DenominatorType.SERVICE_DERIVED,
        coefficient=None,
        multiplier=100000,
        unit="per 100,000 live births",
        direction=IndicatorDirection.LOWER_IS_BETTER,
        target="<=183",
        green="<=183",
        yellow="184-300",
        red=">300",
        blue="Never display as a percentage.",
        period_adjust=False,
        formula_spec=_ratio([MATERNAL_DEATHS], _src(LIVE_BIRTHS)),
        classification_spec={"mode": "mmr"},
    ),
    _indicator(
        code="PERINATAL_REPORTED_DEATHS",
        name="Perinatal reported deaths",
        programme=ProgrammeCode.MPDSR.value,
        numerator="fresh SB + macerated SB + newborn deaths",
        denom_type=DenominatorType.COUNT,
        coefficient=None,
        multiplier=1,
        unit="count",
        direction=IndicatorDirection.NEUTRAL_COUNT,
        target=None,
        green=None,
        yellow=None,
        red=None,
        blue="Count columns remain neutral.",
        period_adjust=False,
        formula_spec={
            "kind": FormulaKind.COUNT.value,
            "source_keys": list(PERINATAL_DEATH_KEYS),
            "require_all_components": True,
        },
        classification_spec={"mode": "neutral_count"},
        precision=0,
    ),
    _indicator(
        code="PERINATAL_NOTIFICATION_COVERAGE",
        name="Perinatal notification coverage",
        programme=ProgrammeCode.MPDSR.value,
        numerator="COMPLETED perinatal notification events",
        denom_type=DenominatorType.EVENT_DERIVED,
        coefficient=None,
        multiplier=100,
        unit="%",
        direction=IndicatorDirection.HIGHER_IS_BETTER,
        target=">=90%",
        green=">=90%",
        yellow="75.0-89.9%",
        red="<75%",
        blue=">100%, unresolved reconciliation, or non-assessable.",
        period_adjust=False,
        formula_spec={
            "kind": FormulaKind.RATIO.value,
            "numerator": {
                "mode": "event_count",
                "event_type": "perinatal_notification",
                "completed_only": True,
            },
            "denominator": _src(*PERINATAL_DEATH_KEYS),
            "over_100": Over100Behaviour.NON_ASSESSABLE.value,
            "reconciliation_blue": True,
        },
        classification_spec=_higher(90, 75),
    ),
    _indicator(
        code="PERINATAL_REVIEW_COVERAGE",
        name="Perinatal review coverage",
        programme=ProgrammeCode.MPDSR.value,
        numerator="COMPLETED perinatal review events",
        denom_type=DenominatorType.EVENT_DERIVED,
        coefficient=None,
        multiplier=100,
        unit="%",
        direction=IndicatorDirection.HIGHER_IS_BETTER,
        target=">=90%",
        green=">=90%",
        yellow="75.0-89.9%",
        red="<75%",
        blue=">100%, unresolved reconciliation, or non-assessable.",
        period_adjust=False,
        formula_spec={
            "kind": FormulaKind.RATIO.value,
            "numerator": {"mode": "event_count", "event_type": "perinatal_review", "completed_only": True},
            "denominator": _src(*PERINATAL_DEATH_KEYS),
            "over_100": Over100Behaviour.NON_ASSESSABLE.value,
            "reconciliation_blue": True,
        },
        classification_spec=_higher(90, 75),
    ),
    _indicator(
        code="PERINATAL_TIMELY_NOTIFICATION",
        name="Perinatal timely notification",
        programme=ProgrammeCode.MPDSR.value,
        numerator="same or next calendar-day completed notifications",
        denom_type=DenominatorType.EVENT_DERIVED,
        coefficient=None,
        multiplier=100,
        unit="%",
        direction=IndicatorDirection.HIGHER_IS_BETTER,
        target=">=90%",
        green=">=90%",
        yellow="75.0-89.9%",
        red="<75%",
        blue="Proxy when only dates are available.",
        period_adjust=False,
        formula_spec={
            "kind": FormulaKind.RATIO.value,
            "numerator": {
                "mode": "event_count",
                "event_type": "perinatal_notification",
                "completed_only": True,
                "timely": "notification",
            },
            "denominator": _src(*PERINATAL_DEATH_KEYS),
            "over_100": Over100Behaviour.NON_ASSESSABLE.value,
        },
        classification_spec=_higher(90, 75),
    ),
    _indicator(
        code="PERINATAL_TIMELY_REVIEW",
        name="Perinatal timely review",
        programme=ProgrammeCode.MPDSR.value,
        numerator="completed reviews within 0–7 days",
        denom_type=DenominatorType.EVENT_DERIVED,
        coefficient=None,
        multiplier=100,
        unit="%",
        direction=IndicatorDirection.HIGHER_IS_BETTER,
        target=">=90%",
        green=">=90%",
        yellow="75.0-89.9%",
        red="<75%",
        blue=None,
        period_adjust=False,
        formula_spec={
            "kind": FormulaKind.RATIO.value,
            "numerator": {
                "mode": "event_count",
                "event_type": "perinatal_review",
                "completed_only": True,
                "timely": "review",
            },
            "denominator": _src(*PERINATAL_DEATH_KEYS),
            "over_100": Over100Behaviour.NON_ASSESSABLE.value,
        },
        classification_spec=_higher(90, 75),
    ),
    _indicator(
        code="MATERNAL_NOTIFICATION_COVERAGE",
        name="Maternal notification coverage",
        programme=ProgrammeCode.MPDSR.value,
        numerator="COMPLETED maternal notification events",
        denom_type=DenominatorType.EVENT_DERIVED,
        coefficient=None,
        multiplier=100,
        unit="%",
        direction=IndicatorDirection.HIGHER_IS_BETTER,
        target="100%",
        green="exactly 100%",
        yellow="90.0-99.9%",
        red="<90%",
        blue="Non-assessable or clear quality conditions.",
        period_adjust=False,
        formula_spec={
            "kind": FormulaKind.RATIO.value,
            "numerator": {
                "mode": "event_count",
                "event_type": "maternal_notification",
                "completed_only": True,
            },
            "denominator": _src(MATERNAL_DEATHS),
            "over_100": Over100Behaviour.NON_ASSESSABLE.value,
            "reconciliation_blue": True,
        },
        classification_spec={"mode": "maternal_coverage"},
    ),
    _indicator(
        code="MATERNAL_REVIEW_COVERAGE",
        name="Maternal review coverage",
        programme=ProgrammeCode.MPDSR.value,
        numerator="COMPLETED maternal review events",
        denom_type=DenominatorType.EVENT_DERIVED,
        coefficient=None,
        multiplier=100,
        unit="%",
        direction=IndicatorDirection.HIGHER_IS_BETTER,
        target="100%",
        green="exactly 100%",
        yellow="90.0-99.9%",
        red="<90%",
        blue="Non-assessable or clear quality conditions.",
        period_adjust=False,
        formula_spec={
            "kind": FormulaKind.RATIO.value,
            "numerator": {"mode": "event_count", "event_type": "maternal_review", "completed_only": True},
            "denominator": _src(MATERNAL_DEATHS),
            "over_100": Over100Behaviour.NON_ASSESSABLE.value,
            "reconciliation_blue": True,
        },
        classification_spec={"mode": "maternal_coverage"},
    ),
    _indicator(
        code="PERINATAL_NOTIFIED_COUNT",
        name="Perinatal deaths notified",
        programme=ProgrammeCode.MPDSR.value,
        numerator="COMPLETED perinatal notification events",
        denom_type=DenominatorType.COUNT,
        coefficient=None,
        multiplier=1,
        unit="count",
        direction=IndicatorDirection.NEUTRAL_COUNT,
        target=None,
        green=None,
        yellow=None,
        red=None,
        blue="Count columns remain neutral.",
        period_adjust=False,
        formula_spec={
            "kind": FormulaKind.COUNT.value,
            "numerator": {
                "mode": "event_count",
                "event_type": "perinatal_notification",
                "completed_only": True,
            },
        },
        classification_spec={"mode": "neutral_count"},
        precision=0,
    ),
    _indicator(
        code="PERINATAL_REVIEWED_COUNT",
        name="Perinatal deaths reviewed",
        programme=ProgrammeCode.MPDSR.value,
        numerator="COMPLETED perinatal review events",
        denom_type=DenominatorType.COUNT,
        coefficient=None,
        multiplier=1,
        unit="count",
        direction=IndicatorDirection.NEUTRAL_COUNT,
        target=None,
        green=None,
        yellow=None,
        red=None,
        blue="Count columns remain neutral.",
        period_adjust=False,
        formula_spec={
            "kind": FormulaKind.COUNT.value,
            "numerator": {"mode": "event_count", "event_type": "perinatal_review", "completed_only": True},
        },
        classification_spec={"mode": "neutral_count"},
        precision=0,
    ),
    _indicator(
        code="MATERNAL_REPORTED_DEATHS",
        name="Maternal deaths reported",
        programme=ProgrammeCode.MPDSR.value,
        numerator="aggregate reported maternal deaths",
        denom_type=DenominatorType.COUNT,
        coefficient=None,
        multiplier=1,
        unit="count",
        direction=IndicatorDirection.NEUTRAL_COUNT,
        target=None,
        green=None,
        yellow=None,
        red=None,
        blue="Count columns remain neutral.",
        period_adjust=False,
        formula_spec={"kind": FormulaKind.COUNT.value, "source_keys": [MATERNAL_DEATHS]},
        classification_spec={"mode": "neutral_count"},
        precision=0,
    ),
    _indicator(
        code="MATERNAL_NOTIFIED_COUNT",
        name="Maternal deaths notified",
        programme=ProgrammeCode.MPDSR.value,
        numerator="COMPLETED maternal notification events",
        denom_type=DenominatorType.COUNT,
        coefficient=None,
        multiplier=1,
        unit="count",
        direction=IndicatorDirection.NEUTRAL_COUNT,
        target=None,
        green=None,
        yellow=None,
        red=None,
        blue="Count columns remain neutral.",
        period_adjust=False,
        formula_spec={
            "kind": FormulaKind.COUNT.value,
            "numerator": {
                "mode": "event_count",
                "event_type": "maternal_notification",
                "completed_only": True,
            },
        },
        classification_spec={"mode": "neutral_count"},
        precision=0,
    ),
    _indicator(
        code="MATERNAL_REVIEWED_COUNT",
        name="Maternal deaths reviewed",
        programme=ProgrammeCode.MPDSR.value,
        numerator="COMPLETED maternal review events",
        denom_type=DenominatorType.COUNT,
        coefficient=None,
        multiplier=1,
        unit="count",
        direction=IndicatorDirection.NEUTRAL_COUNT,
        target=None,
        green=None,
        yellow=None,
        red=None,
        blue="Count columns remain neutral.",
        period_adjust=False,
        formula_spec={
            "kind": FormulaKind.COUNT.value,
            "numerator": {"mode": "event_count", "event_type": "maternal_review", "completed_only": True},
        },
        classification_spec={"mode": "neutral_count"},
        precision=0,
    ),
    _indicator(
        code="MATERNAL_TIMELY_NOTIFICATION",
        name="Maternal timely notification",
        programme=ProgrammeCode.MPDSR.value,
        numerator="completed verifiable same/next-day maternal notifications",
        denom_type=DenominatorType.EVENT_DERIVED,
        coefficient=None,
        multiplier=100,
        unit="%",
        direction=IndicatorDirection.HIGHER_IS_BETTER,
        target="100%",
        green="exactly 100%",
        yellow="90.0-99.9%",
        red="<90%",
        blue="BLUE when non-assessable.",
        period_adjust=False,
        formula_spec={
            "kind": FormulaKind.RATIO.value,
            "numerator": {
                "mode": "event_count",
                "event_type": "maternal_notification",
                "completed_only": True,
                "timely": "notification",
            },
            "denominator": _src(MATERNAL_DEATHS),
            "over_100": Over100Behaviour.NON_ASSESSABLE.value,
            "reconciliation_blue": True,
        },
        classification_spec={"mode": "maternal_coverage", "precision": 1},
    ),
    _indicator(
        code="MATERNAL_TIMELY_REVIEW",
        name="Maternal timely review",
        programme=ProgrammeCode.MPDSR.value,
        numerator="completed reviews within 0–7 calendar days",
        denom_type=DenominatorType.EVENT_DERIVED,
        coefficient=None,
        multiplier=100,
        unit="%",
        direction=IndicatorDirection.HIGHER_IS_BETTER,
        target="100%",
        green="exactly 100%",
        yellow="90.0-99.9%",
        red="<90%",
        blue="BLUE when non-assessable.",
        period_adjust=False,
        formula_spec={
            "kind": FormulaKind.RATIO.value,
            "numerator": {
                "mode": "event_count",
                "event_type": "maternal_review",
                "completed_only": True,
                "timely": "review",
            },
            "denominator": _src(MATERNAL_DEATHS),
            "over_100": Over100Behaviour.NON_ASSESSABLE.value,
            "reconciliation_blue": True,
        },
        classification_spec={"mode": "maternal_coverage", "precision": 1},
    ),
]


def _epi_coverage(code: str, name: str, source_key: str, coefficient: float) -> dict:
    return _indicator(
        code=code,
        name=name,
        programme=ProgrammeCode.EPI.value,
        numerator=f"{source_key} doses administered",
        denom_type=DenominatorType.POPULATION_DERIVED,
        coefficient=coefficient,
        multiplier=100,
        unit="%",
        direction=IndicatorDirection.HIGHER_IS_BETTER,
        target=None,
        green=None,
        yellow=None,
        red=None,
        blue="EPI performance bands remain TBD and must not be invented.",
        period_adjust=True,
        formula_spec=_ratio([source_key], _pop(coefficient), over_100=Over100Behaviour.RETAIN_PERFORMANCE.value),
        classification_spec={"mode": "unclassified"},
    )


EPI_COVERAGE_SPECS = [
    ("BCG_COVERAGE", "BCG coverage", "BCG", 0.0485),
    ("OPV0_COVERAGE", "OPV0 coverage", "OPV0", 0.0485),
    ("HEPB_BIRTH_COVERAGE", "Hepatitis-B birth dose coverage", "HEPB_BIRTH", 0.0485),
    ("OPV1_COVERAGE", "OPV1 coverage", "OPV1", 0.043),
    ("OPV2_COVERAGE", "OPV2 coverage", "OPV2", 0.043),
    ("OPV3_COVERAGE", "OPV3 coverage", "OPV3", 0.043),
    ("PENTA1_COVERAGE", "DPT-HepB-Hib1 coverage", "PENTA1", 0.043),
    ("PENTA2_COVERAGE", "DPT-HepB-Hib2 coverage", "PENTA2", 0.043),
    ("PENTA3_COVERAGE", "DPT-HepB-Hib3 coverage", "PENTA3", 0.043),
    ("ROTAV1_COVERAGE", "RotaV1 coverage", "ROTAV1", 0.043),
    ("ROTAV2_COVERAGE", "RotaV2 coverage", "ROTAV2", 0.043),
    ("PCV1_COVERAGE", "PCV1 coverage", "PCV1", 0.043),
    ("PCV2_COVERAGE", "PCV2 coverage", "PCV2", 0.043),
    ("PCV3_COVERAGE", "PCV3 coverage", "PCV3", 0.043),
    ("IPV1_COVERAGE", "IPV1 coverage", "IPV1", 0.043),
    ("IPV2_COVERAGE", "IPV2 coverage", "IPV2", 0.043),
    ("MR_COVERAGE", "Measles-Rubella coverage", "MR", 0.043),
    ("YF_COVERAGE", "Yellow Fever coverage", "YF", 0.043),
    ("MV1_COVERAGE", "Malaria Vaccine Dose 1 Coverage", "MV1", 0.043),
    ("MV2_COVERAGE", "Malaria Vaccine Dose 2 Coverage", "MV2", 0.043),
    ("MV3_COVERAGE", "Malaria Vaccine Dose 3 Coverage", "MV3", 0.043),
    ("MV4_COVERAGE", "Malaria Vaccine Dose 4 Coverage", "MV4", 0.043),
    ("TD_1549_COVERAGE", "Td women 15–49 coverage", "TD_1549", 0.23),
    ("HPV_COVERAGE", "HPV girls coverage", "HPV", 0.0153),
    ("VITA_6_11_COVERAGE", "Vitamin A 6–11 months coverage", "VITA_6_11", 0.0193),
    ("VITA_12_59_COVERAGE", "Vitamin A 12–59 months coverage", "VITA_12_59", 0.162),
    ("DEWORM_1_14_COVERAGE", "Deworming 1–14 years coverage", "DEWORM_1_14", 0.493),
    ("UNDER5_COVERAGE", "Under-5 target coverage", "UNDER5", 0.205),
]

INDICATOR_CATALOG.extend(_epi_coverage(*row) for row in EPI_COVERAGE_SPECS)

INDICATOR_CATALOG.append(
    _indicator(
        code="MV1_MV4_DROPOUT",
        name="MV1 to MV4 dropout",
        programme=ProgrammeCode.EPI.value,
        numerator="(MV1 − MV4) / MV1",
        denom_type=DenominatorType.SERVICE_DERIVED,
        coefficient=None,
        multiplier=100,
        unit="%",
        direction=IndicatorDirection.LOWER_IS_BETTER,
        target=None,
        green=None,
        yellow=None,
        red=None,
        blue="EPI dropout thresholds are not invented. The value is calculated and left unclassified.",
        period_adjust=False,
        formula_spec={
            "kind": FormulaKind.DROPOUT.value,
            "first_key": "MV1",
            "final_key": "MV4",
        },
        classification_spec={"mode": "unclassified"},
    )
)

INDICATOR_CATALOG.append(
    _indicator(
        code="PENTA_DROPOUT",
        name="Penta1 to Penta3 dropout",
        programme=ProgrammeCode.EPI.value,
        numerator="(Penta1 − Penta3) / Penta1",
        denom_type=DenominatorType.SERVICE_DERIVED,
        coefficient=None,
        multiplier=100,
        unit="%",
        direction=IndicatorDirection.LOWER_IS_BETTER,
        target=None,
        green=None,
        yellow=None,
        red=None,
        blue="Dropout thresholds remain configurable/TBD.",
        period_adjust=False,
        formula_spec={
            "kind": FormulaKind.DROPOUT.value,
            "first_key": "PENTA1",
            "final_key": "PENTA3",
        },
        classification_spec={"mode": "unclassified"},
    )
)

INDICATOR_BY_CODE = {row["code"]: row for row in INDICATOR_CATALOG}


QUALITY_RULE_CATALOG: list[dict] = [
    {
        "code": "BOUNDED_PROPORTION_OVER_100",
        "category": "validity",
        "severity": "ERROR",
        "explanation": (
            "The calculated proportion exceeds 100%, which is logically "
            "impossible for this bounded measure."
        ),
    },
    {
        "code": "NUMERATOR_GT_DENOMINATOR",
        "category": "validity",
        "severity": "ERROR",
        "explanation": "The numerator is greater than the denominator where that is logically impossible.",
    },
    {
        "code": "MISSING_DENOMINATOR",
        "category": "completeness",
        "severity": "BLOCKING",
        "explanation": "A denominator is missing, so the indicator cannot be assessed.",
    },
    {
        "code": "MISSING_POPULATION",
        "category": "completeness",
        "severity": "BLOCKING",
        "explanation": (
            "Population is unavailable for this geography and year. "
            "Service-derived indicators are unaffected."
        ),
    },
    {
        "code": "DENOMINATOR_ZERO",
        "category": "validity",
        "severity": "BLOCKING",
        "explanation": "The denominator is zero. The result is non-assessable, not zero percent.",
    },
    {
        "code": "NO_DATA_VS_REPORTED_ZERO",
        "category": "completeness",
        "severity": "WARNING",
        "explanation": "Absence of a source row is distinct from a reported zero and was preserved.",
    },
    {
        "code": "AGGREGATE_EVENT_MISMATCH",
        "category": "reconciliation",
        "severity": "ERROR",
        "explanation": (
            "Aggregate reported deaths and the event line-list count differ. "
            "Reconciliation is required; the cause is not inferred."
        ),
    },
    {
        "code": "LINELIST_GT_AGGREGATE",
        "category": "reconciliation",
        "severity": "ERROR",
        "explanation": (
            "The line-list count exceeds aggregate reported deaths. Reconciliation is required. "
            "Possible checks include duplication, delayed aggregate reporting, "
            "or under-reporting; the system does not choose among them."
        ),
    },
    {
        "code": "ACTIVE_MPDSR_WORKFLOW",
        "category": "workflow",
        "severity": "INFO",
        "explanation": (
            "The event is ACTIVE and must display as Active (not completed). "
            "It is excluded from completed numerators."
        ),
    },
    {
        "code": "NOTIFICATION_BEFORE_DEATH",
        "category": "chronology",
        "severity": "ERROR",
        "explanation": "Notification date is before the recorded death date. The chronology is invalid.",
    },
    {
        "code": "REVIEW_BEFORE_DEATH",
        "category": "chronology",
        "severity": "ERROR",
        "explanation": "Review date is before the recorded death date. The chronology is invalid.",
    },
    {
        "code": "REVIEW_INTERVAL_OUT_OF_RANGE",
        "category": "timeliness",
        "severity": "WARNING",
        "explanation": "The review interval is outside the configured 0–7 calendar days after death.",
    },
    {
        "code": "MISSING_CAUSE",
        "category": "completeness",
        "severity": "WARNING",
        "explanation": "A completed review has no structured cause documentation.",
    },
    {
        "code": "MISSING_CRITICAL_DATE",
        "category": "completeness",
        "severity": "ERROR",
        "explanation": "A critical event date (death, notification, or review) is missing.",
    },
    {
        "code": "POSSIBLE_DUPLICATE_EVENT",
        "category": "reconciliation",
        "severity": "WARNING",
        "explanation": (
            "More than one event shares facility, death date, and type. "
            "Reconciliation is required before removal."
        ),
    },
    {
        "code": "UNEXPECTED_ZERO",
        "category": "anomaly",
        "severity": "WARNING",
        "explanation": "A reported zero follows a configured non-zero history or appears at a high-volume site.",
    },
    {
        "code": "ANOMALOUS_SPIKE_DROP",
        "category": "anomaly",
        "severity": "WARNING",
        "explanation": (
            "A configured deterministic spike/drop rule fired. "
            "The reference period is included in evidence."
        ),
    },
    {
        "code": "STALE_REPORTING",
        "category": "freshness",
        "severity": "WARNING",
        "explanation": "The latest expected reporting period is missing or older than the configured freshness window.",
    },
    {
        "code": "STALE_ANALYTICS",
        "category": "freshness",
        "severity": "WARNING",
        "explanation": "Event Analytics freshness lags Tracker. The two sources are not identical snapshots.",
    },
    {
        "code": "MAPPING_MISSING",
        "category": "metadata",
        "severity": "ERROR",
        "explanation": "No enabled source mapping exists for a required semantic field.",
    },
    {
        "code": "METADATA_DRIFT",
        "category": "metadata",
        "severity": "WARNING",
        "explanation": "Mapped metadata identifiers changed between extraction runs.",
    },
    {
        "code": "PARENT_CHILD_RECONCILIATION",
        "category": "reconciliation",
        "severity": "WARNING",
        "explanation": (
            "Parent and child values cannot be mixed without double counting. "
            "A consistent level was required."
        ),
    },
    {
        "code": "FACILITY_POPULATION_PENDING_APPROVAL",
        "category": "governance",
        "severity": "WARNING",
        "explanation": "A facility catchment population exists but is not approved, so it was not used in calculation.",
    },
    {
        "code": "SOURCE_FRESHNESS_MISMATCH",
        "category": "freshness",
        "severity": "WARNING",
        "explanation": "Event Analytics and Tracker freshness times differ. Analytics may lag current Tracker state.",
    },
    {
        "code": "INCOMPLETE_COMPOSITE",
        "category": "completeness",
        "severity": "BLOCKING",
        "explanation": (
            "A required composite component is missing. The composite is unavailable "
            "and missing is not treated as zero."
        ),
    },
    {
        "code": "INVALID_SOURCE_VALUE",
        "category": "validity",
        "severity": "ERROR",
        "explanation": (
            "The source supplied a nonnumeric or otherwise invalid value. "
            "The row was rejected, not converted to missing."
        ),
    },
    {
        "code": "INCOMPLETE_CHILD_COVERAGE",
        "category": "completeness",
        "severity": "WARNING",
        "explanation": (
            "Child reporting at the selected consistent level is incomplete, "
            "so the parent aggregate is non-assessable."
        ),
    },
    {
        "code": "MAPPING_AMBIGUOUS",
        "category": "metadata",
        "severity": "ERROR",
        "explanation": "Enabled mappings collide for the same programme, version, and category context.",
    },
    {
        "code": "INCOMPATIBLE_AGGREGATION_SCOPE",
        "category": "reconciliation",
        "severity": "ERROR",
        "explanation": (
            "Formula components do not share one geography and aggregation scope (for example a parent row "
            "for the numerator with child rows for the denominator, mixed levels, or incompatible mapping "
            "versions). The value is unavailable; nothing was combined."
        ),
    },
    {
        "code": "MPDSR_EVENT_COVERAGE_UNVERIFIED",
        "category": "completeness",
        "severity": "WARNING",
        "explanation": (
            "No successful, complete, current and appropriately scoped MPDSR synchronisation proves this event "
            "cohort. An empty cohort is not reported as zero, and observed counts may be incomplete."
        ),
    },
    {
        "code": "POPULATION_RULE_MISSING",
        "category": "configuration",
        "severity": "BLOCKING",
        "explanation": (
            "No approved period-population rule covers this reporting period kind, so population-derived "
            "values are unavailable. Service-derived values are unaffected."
        ),
    },
]
