from functools import lru_cache

from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

from app.db.urls import driver_error, is_postgres, is_well_formed, normalise_database_url, tls_errors

DEV_TEST_ENVS = frozenset({"development", "dev", "test"})
PLACEHOLDER_CREDENTIALS = ("change-me", "changeme", "replace-with-", "dev-only-")


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=("../.env", ".env"),
        env_file_encoding="utf-8",
        extra="ignore",
    )

    app_name: str = "Uganda Health Performance Intelligence Platform"
    app_env: str = "development"
    api_host: str = "0.0.0.0"
    api_port: int = 8000
    web_origin: str = "http://localhost:3000"
    log_level: str = "INFO"

    database_url: str = Field(
        default="sqlite+pysqlite:///./hpip_dev.db",
        description="SQLAlchemy URL. PostgreSQL is required for shared/staging/production.",
    )
    # Optional direct (unpooled) URL for migrations when DATABASE_URL is a pooled endpoint,
    # as it is on Neon. Provider-neutral: only the URL differs.
    migration_database_url: str = ""
    # Small pools on purpose: the API, worker, migration job and scheduled purge share one
    # managed database with a limited connection budget.
    db_pool_size: int = Field(default=5, ge=1, le=50)
    db_max_overflow: int = Field(default=5, ge=0, le=50)
    db_pool_recycle_seconds: int = Field(default=300, ge=30, le=86_400)
    db_pool_timeout_seconds: int = Field(default=30, ge=1, le=300)
    db_pool_pre_ping: bool = True
    db_connect_timeout_seconds: int = Field(default=10, ge=1, le=120)
    # "require" for managed PostgreSQL; empty leaves the driver default (local development).
    db_sslmode: str = ""
    # Managed databases must be reached over TLS. Set false only for a database on a private
    # network you control (for example the Docker Compose stack), and say so in deployment docs.
    db_require_ssl: bool = True
    db_application_name: str = "hpip"

    auth_secret: str = Field(
        default="replace-with-a-long-random-development-secret-at-least-32-chars",
        min_length=32,
    )
    auth_token_ttl_minutes: int = 120
    auth_cookie_name: str = "hpip_session"
    auth_cookie_secure: bool = False
    auth_cookie_samesite: str = "lax"
    auth_csrf_cookie_name: str = "hpip_csrf"
    auth_csrf_header_name: str = "x-csrf-token"
    auth_issuer: str = "hpip-api"
    auth_audience: str = "hpip-web"
    login_max_attempts: int = 8
    login_window_seconds: int = 300
    population_year_min: int = 2000
    population_year_max: int = 2100
    sync_execution: str = "queue"

    seed_dev_data: bool = False
    seed_password: str = "dev-only-change-me"

    # The host is known, but nothing is connected: credentials, verified mappings and live
    # synchronisation are still missing. Both switches must be set explicitly to enable them.
    dhis2_enabled: bool = False
    sync_enabled: bool = False
    dhis2_base_url: str = ""
    dhis2_username: str = ""
    dhis2_password: str = ""
    dhis2_pat: str = ""
    dhis2_auth_method: str = "basic"
    dhis2_api_path_prefix: str = "/api"
    dhis2_timeout_seconds: int = 30
    dhis2_max_retries: int = 3
    dhis2_retry_base_seconds: float = 0.2
    dhis2_retry_max_seconds: float = 4.0
    dhis2_page_size: int = 200
    dhis2_max_pages: int = 50
    dhis2_max_response_bytes: int = 5_000_000
    dhis2_ou_mode: str = "DESCENDANTS"
    dhis2_stale_hours: int = 72

    # No broker or Redis default: staging/production must configure them explicitly and fail
    # closed when they are missing. Development and test opt in to local values in `.env`.
    redis_url: str = ""
    celery_broker_url: str = ""
    celery_result_backend: str = ""
    # "redis" (distributed) or "memory" (per-process, development/test only and only when set).
    rate_limit_backend: str = "redis"

    ai_provider: str = ""
    ai_base_url: str = ""
    ai_api_key: str = ""
    ai_model: str = ""
    ai_enabled: bool = False
    ai_timeout_seconds: float = 20.0
    ai_max_tokens: int = 800
    ai_prompt_version: str = "hpip-ai-2"
    ai_max_evidence_chars: int = 20000
    export_dir: str = "./export_artifacts"
    export_rate_limit: int = 30
    ai_rate_limit: int = 20
    allowed_hosts: str = "localhost,127.0.0.1"
    allowed_origins: str = "http://localhost:3000"
    trusted_proxy_ips: str = ""
    hsts_enabled: bool = False
    query_count_warn: int = 800
    # Exports are generated by the Celery worker. In-request (eager) generation is refused
    # unless EXPORT_EAGER=true is set explicitly in a development or test environment.
    export_eager: bool = False
    export_queue_name: str = "exports"
    # Where finished export bytes live. "filesystem" needs one disk shared by the API and the
    # worker; "database" keeps small aggregated files in PostgreSQL for platforms (Render) where
    # each service has its own ephemeral disk. Bytes always expire with EXPORT_FILE_RETENTION_HOURS.
    export_artifact_storage: str = "filesystem"
    export_artifact_max_bytes: int = Field(default=26_214_400, ge=1024, le=104_857_600)
    # Set false when the API and worker do not share EXPORT_DIR (separate hosts/containers).
    export_shared_filesystem: bool = True
    export_max_attempts: int = Field(default=3, ge=1, le=10)
    export_retry_backoff_seconds: int = Field(default=15, ge=1)
    export_retry_backoff_max_seconds: int = Field(default=300, ge=1)
    export_job_lease_seconds: int = Field(default=900, ge=60)
    sync_queue_name: str = "sync"
    maintenance_queue_name: str = "maintenance"
    # Undated (legacy) formula versions may be used only when an indicator has no dated
    # history. Unset: permitted in development/test only. Staging/production must set it.
    formula_undated_fallback: bool | None = None
    # MPDSR cause patterns stay withheld until an owner-approved minimum cell size is set.
    mpdsr_cause_min_cell_count: int | None = None

    # ---------------------------------------------------------------------
    # Retention (owner decision 2026-09-14). HPIP is a control and results
    # store, never a second HMIS warehouse: routine raw data is a short-lived
    # cache, while calculated evidence, provenance and audit are retained.
    # All windows are configurable; month windows use calendar months.
    # ---------------------------------------------------------------------
    raw_aggregate_retention_days: int = Field(default=7, ge=1, le=3650)
    mpdsr_event_retention_hours: int = Field(default=24, ge=1, le=8760)
    export_file_retention_hours: int = Field(default=24, ge=1, le=8760)
    export_job_retention_days: int = Field(default=90, ge=1, le=3650)
    calculation_snapshot_retention_months: int = Field(default=36, ge=1, le=600)
    audit_log_retention_months: int = Field(default=24, ge=1, le=600)
    # Engineering default, not an owner decision (see OPEN_ITEMS): maintenance run records and
    # operational events are counts and codes only, kept as long as export job metadata.
    operational_record_retention_days: int = Field(default=90, ge=1, le=3650)
    purge_enabled: bool = True
    purge_dry_run: bool = False
    purge_schedule_enabled: bool = False
    purge_batch_size: int = Field(default=500, ge=1, le=10_000)
    purge_max_batches: int = Field(default=200, ge=1, le=10_000)
    purge_lock_timeout_seconds: int = Field(default=900, ge=30, le=86_400)

    @property
    def cors_origins(self) -> list[str]:
        configured = [item.strip() for item in self.allowed_origins.split(",") if item.strip()]
        if self.app_env in {"development", "test", "dev"}:
            extras = [self.web_origin, "http://localhost:3000"]
            return list(dict.fromkeys([*configured, *extras]))
        return [item for item in configured if "localhost" not in item and "127.0.0.1" not in item] or [self.web_origin]

    @property
    def host_list(self) -> list[str]:
        return [item.strip() for item in self.allowed_hosts.split(",") if item.strip()]

    @field_validator("app_env")
    @classmethod
    def normalize_env(cls, value: str) -> str:
        return value.lower().strip()

    @field_validator("database_url", "migration_database_url", mode="before")
    @classmethod
    def normalise_database_driver(cls, value: object) -> object:
        # Never raise here: a validation error would echo the URL (and its password).
        return normalise_database_url(value) if isinstance(value, str) else value

    @property
    def is_sqlite(self) -> bool:
        return self.database_url.startswith("sqlite")

    @property
    def is_production(self) -> bool:
        return self.app_env in {"production", "prod", "staging"}

    @property
    def is_dev_or_test(self) -> bool:
        return self.app_env in DEV_TEST_ENVS

    @property
    def undated_formula_policy(self) -> str:
        """How undated legacy formula versions are governed for this environment."""
        if self.formula_undated_fallback is True:
            return "explicitly_enabled"
        if self.formula_undated_fallback is False:
            return "disabled"
        return "development_default" if self.is_dev_or_test else "not_configured"

    @property
    def undated_formula_fallback_permitted(self) -> bool:
        return self.undated_formula_policy in {"explicitly_enabled", "development_default"}


@lru_cache
def get_settings() -> Settings:
    return Settings()


def validate_runtime_settings(settings: Settings) -> list[str]:
    """Return blocking configuration errors. Used by readiness and tests."""
    errors: list[str] = []
    if len(settings.auth_secret) < 32:
        errors.append("AUTH_SECRET must be at least 32 characters.")
    if settings.auth_secret.startswith("replace-with-"):
        if settings.is_production:
            errors.append("AUTH_SECRET is still the placeholder value.")
    if settings.is_production and settings.seed_dev_data:
        errors.append("SEED_DEV_DATA must be false outside local development.")
    if settings.is_production and settings.seed_password == "dev-only-change-me":
        errors.append("SEED_PASSWORD must not use the documented development default.")
    if settings.is_production and settings.is_sqlite:
        errors.append("DATABASE_URL must be PostgreSQL in staging/production.")
    if settings.is_production and settings.ai_enabled and not settings.ai_api_key:
        errors.append("AI_API_KEY is required when AI_ENABLED is true.")
    if settings.dhis2_password and "dhis2_password" in settings.dhis2_password.lower():
        errors.append("DHIS2_PASSWORD appears to be a placeholder.")
    if settings.is_production and settings.sync_execution != "queue":
        errors.append("SYNC_EXECUTION must be queue in staging/production.")
    if settings.is_production and not settings.auth_cookie_secure:
        errors.append("AUTH_COOKIE_SECURE must be true behind HTTPS.")
    if settings.is_production and settings.auth_cookie_samesite.lower() == "none" and not settings.auth_cookie_secure:
        errors.append("SameSite=None requires AUTH_COOKIE_SECURE.")
    if settings.is_production and ("change-me" in settings.database_url or "hpip:change-me" in settings.database_url):
        errors.append("DATABASE_URL still uses a documented placeholder credential.")
    if settings.is_production and settings.web_origin.startswith("http://"):
        errors.append("WEB_ORIGIN must be HTTPS in staging/production.")
    if settings.is_production and settings.ai_enabled and settings.ai_base_url and not settings.ai_base_url.startswith("https://"):
        errors.append("AI_BASE_URL must be HTTPS when AI is enabled.")
    if settings.is_production and settings.dhis2_base_url and not settings.dhis2_base_url.startswith("https://"):
        errors.append("DHIS2_BASE_URL must be HTTPS in staging/production.")
    if settings.is_production and not settings.host_list:
        errors.append("ALLOWED_HOSTS must be configured.")
    if "*" in settings.cors_origins and settings.is_production:
        errors.append("CORS must not use wildcard origins with credentials.")
    if settings.export_eager and not settings.is_dev_or_test:
        errors.append("EXPORT_EAGER must be false outside development/test so workers generate artifacts.")
    errors.extend(queue_configuration_errors(settings))
    errors.extend(rate_limit_configuration_errors(settings))
    errors.extend(retention_configuration_errors(settings))
    errors.extend(artifact_storage_configuration_errors(settings))
    errors.extend(database_configuration_errors(settings))
    errors.extend(dhis2_configuration_errors(settings))
    return errors


def dhis2_configuration_errors(settings: Settings) -> list[str]:
    """DHIS2 stays inert until it is switched on deliberately, and then it must be complete."""
    errors: list[str] = []
    if not settings.dhis2_enabled:
        if settings.sync_enabled:
            errors.append("SYNC_ENABLED requires DHIS2_ENABLED.")
        return errors
    if not settings.dhis2_base_url.strip():
        errors.append("DHIS2_BASE_URL is required when DHIS2_ENABLED is true.")
    elif not settings.dhis2_base_url.startswith("https://"):
        errors.append("DHIS2_BASE_URL must be HTTPS when DHIS2_ENABLED is true.")
    method = settings.dhis2_auth_method.strip().lower()
    if method == "basic" and not (settings.dhis2_username and settings.dhis2_password):
        errors.append("DHIS2 basic authentication requires DHIS2_USERNAME and DHIS2_PASSWORD.")
    if method in {"pat", "token"} and not settings.dhis2_pat:
        errors.append("DHIS2 token authentication requires DHIS2_PAT.")
    return errors


def database_configuration_errors(settings: Settings) -> list[str]:
    """Connection problems that must stop a staging/production deployment."""
    errors: list[str] = []
    url = settings.database_url.strip()
    if not url:
        errors.append("DATABASE_URL is required.")
        return errors
    if not is_well_formed(url):
        errors.append("DATABASE_URL is malformed.")
        return errors
    migration = settings.migration_database_url.strip()
    if migration and not is_well_formed(migration):
        errors.append("MIGRATION_DATABASE_URL is malformed.")
        migration = ""
    for label, value in (("DATABASE_URL", url), ("MIGRATION_DATABASE_URL", migration)):
        problem = driver_error(value, label)
        if problem:
            errors.append(problem)
    if not settings.is_production:
        return errors
    if settings.is_sqlite:
        errors.append("DATABASE_URL must be PostgreSQL in staging/production.")
        return errors
    if not is_postgres(url):
        errors.append("DATABASE_URL must use a PostgreSQL driver in staging/production.")
    if migration and not is_postgres(migration):
        errors.append("MIGRATION_DATABASE_URL must use a PostgreSQL driver.")
    errors.extend(
        tls_errors(url, "DATABASE_URL", configured=settings.db_sslmode, require_ssl=settings.db_require_ssl)
    )
    if migration:
        errors.extend(
            tls_errors(
                migration,
                "MIGRATION_DATABASE_URL",
                configured=settings.db_sslmode,
                require_ssl=settings.db_require_ssl,
            )
        )
    if migration and any(marker in migration.lower() for marker in PLACEHOLDER_CREDENTIALS):
        errors.append("MIGRATION_DATABASE_URL still uses a documented placeholder credential.")
    if settings.db_pool_size + settings.db_max_overflow > 20:
        errors.append("DB_POOL_SIZE plus DB_MAX_OVERFLOW is too large for a small managed database.")
    return errors


def artifact_storage_configuration_errors(settings: Settings) -> list[str]:
    """A worker must never write exports to a disk the API cannot read."""
    errors: list[str] = []
    storage = settings.export_artifact_storage.strip().lower()
    if storage not in {"filesystem", "database"}:
        errors.append("EXPORT_ARTIFACT_STORAGE must be 'filesystem' or 'database'.")
        return errors
    if storage == "filesystem" and not settings.export_shared_filesystem:
        errors.append(
            "EXPORT_ARTIFACT_STORAGE=filesystem requires a filesystem shared by the API and worker; "
            "set EXPORT_SHARED_FILESYSTEM=true or use EXPORT_ARTIFACT_STORAGE=database."
        )
    return errors


def retention_configuration_errors(settings: Settings) -> list[str]:
    """Retention windows must stay coherent: evidence outlives the raw cache it came from."""
    errors: list[str] = []
    if settings.export_job_retention_days * 24 < settings.export_file_retention_hours:
        errors.append("EXPORT_JOB_RETENTION_DAYS must cover EXPORT_FILE_RETENTION_HOURS.")
    if settings.calculation_snapshot_retention_months * 28 * 24 < settings.raw_aggregate_retention_days * 24:
        errors.append("CALCULATION_SNAPSHOT_RETENTION_MONTHS must exceed RAW_AGGREGATE_RETENTION_DAYS.")
    if settings.is_production and settings.purge_dry_run and settings.purge_schedule_enabled:
        errors.append("PURGE_DRY_RUN must be false when PURGE_SCHEDULE_ENABLED is true in staging/production.")
    if settings.is_production and not settings.purge_enabled:
        errors.append("PURGE_ENABLED must be true in staging/production so expired data is removed.")
    return errors


def queue_configuration_errors(settings: Settings) -> list[str]:
    """Broker problems that block queued work. Development/test with EXPORT_EAGER are exempt."""
    errors: list[str] = []
    broker = settings.celery_broker_url.strip()
    if not broker:
        if settings.is_production:
            errors.append("CELERY_BROKER_URL is required in staging/production.")
        return errors
    if broker.startswith("memory://") and not settings.is_dev_or_test:
        errors.append("CELERY_BROKER_URL must not use the in-memory transport outside development/test.")
    if settings.is_production and any(marker in broker.lower() for marker in PLACEHOLDER_CREDENTIALS):
        errors.append("CELERY_BROKER_URL still uses a documented placeholder credential.")
    if settings.is_production and not settings.celery_result_backend.strip():
        errors.append("CELERY_RESULT_BACKEND is required in staging/production.")
    return errors


def rate_limit_configuration_errors(settings: Settings) -> list[str]:
    errors: list[str] = []
    backend = settings.rate_limit_backend.strip().lower()
    if backend not in {"redis", "memory"}:
        errors.append("RATE_LIMIT_BACKEND must be 'redis' or 'memory'.")
    elif backend == "memory" and not settings.is_dev_or_test:
        errors.append("RATE_LIMIT_BACKEND=memory is per-process and only permitted in development/test.")
    elif backend == "redis" and not settings.redis_url.strip() and settings.is_production:
        errors.append("REDIS_URL is required for distributed rate limiting in staging/production.")
    if settings.is_production and any(marker in settings.redis_url.lower() for marker in PLACEHOLDER_CREDENTIALS):
        errors.append("REDIS_URL still uses a documented placeholder credential.")
    return errors
